
all:	Nodo.class  Main.class

Main.class: Main.java Nodo.class
			@javac Main.java

Nodo.class: Nodo.java
			@javac Nodo.java

RMIStart.class: RMIStart.java
			@javac RMIStart.java

clean:
			@rm -rf *.class *~